In [60]:
# string program

str="sureshsainiswatipushpaaaabb"
counta=0
countb=0

for i in str:
    if i=="a": 
        counta+=1
    elif i=="b":
        countb+=1
        

print("number of a :",counta,"number of b :",countb)
print(len(str),"length of the string ")

number of a : 6 number of b : 2
27 length of the string 


In [78]:
# with function string calling and return

str="sureshsainiswatipushpaaaabb"
def stringcount(str):
    counta=0
    countb=0

    for i in str:
        if i=="a": 
            counta+=1
        elif i=="b":
            countb+=1
    return counta,countb
stringcount(str)

(6, 2)

In [100]:
# reverse string 

str1="I Love MY INDIA"

print(str1[::-1])        

AIDNI YM evoL I


In [99]:

str1="I Love MY INDIA"
empstr=" "
print(empstr.join(reversed(str1)))      

A I D N I   Y M   e v o L   I


In [107]:
str2=str1.split()
print(str2)

['I', 'Love', 'MY', 'INDIA']


In [105]:
str2[::-1]

['INDIA', 'MY', 'Love', 'I']

In [2]:
strin="I Love MY INDIA"
def revs(strin):
    str21=strin.split()
    str31=str21[::-1]
    return str31

revs(strin)    

['INDIA', 'MY', 'Love', 'I']

In [58]:
# all the 26 letters ato z

strname="aafffkk"

countdict={}
listabc=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

for listi in listabc:
    count=0
    for stri in strname:
        
        if listi==stri:
            count+=1
            #countlist+=1
    if count!=0:
        
        print("counting ...",listi,count)
        countdict[listi]=count

print(countdict)

    
    

counting ... a 2
counting ... f 3
counting ... k 2
{'a': 2, 'f': 3, 'k': 2}


In [27]:
lista=['a','b','c']
for i in lista:
    print(i)

a
b
c


In [78]:
input_str="wweetttaaaa"
count_dict={}
for c in input_str:
    if c in count_dict:
        count_dict[c]=count_dict[c]+1
        print("IF ",c,count_dict[c])
    else:
        count_dict[c]=1
        print("else  ",c,count_dict[c])


else   w 1
IF  w 2
else   e 1
IF  e 2
else   t 1
IF  t 2
IF  t 3
else   a 1
IF  a 2
IF  a 3
IF  a 4


In [79]:
count_dict

{'w': 2, 'e': 2, 't': 3, 'a': 4}

In [83]:
for i in count_dict.values():
    print(i)

2
2
3
4


In [84]:
for i in count_dict.items():
    print(i)

('w', 2)
('e', 2)
('t', 3)
('a', 4)


In [85]:
import numpy as np
a= np.array([20,30,100,60])
print(a)

[ 20  30 100  60]


In [86]:
a

array([ 20,  30, 100,  60])

In [87]:
np.argsort(a) # using indexing it gives us assending order

array([0, 1, 3, 2])

In [88]:
np.argsort(a)[-2:] # assending highest order largest

array([3, 2])

In [91]:
np.argsort(a)[-2:][::-1] # desending order 

array([2, 3])

In [93]:
import pandas as pd
l1=[1,2,3,4,5]
pd.DataFrame(l1)

0
0  1
1  2
2  3
3  4
4  5

In [95]:
dt1={'fruite_name':['apple','mango'],'count':[12,24]}
pd.DataFrame(dt1)

fruite_name  count
0       apple     12
1       mango     24

In [97]:
x=lambda a:a+10

In [98]:
x(100)

110

In [100]:
import numpy as np
from matplotlib import pyplot as plt
x=np.arange(0,10,1)

ModuleNotFoundError: No module named 'matplotlib'

In [101]:
x

<function __main__.<lambda>(a)>

In [ ]:
plt.plot(x,y)
plt.xlabel("x_axis")
